# Generated by Django 5.1.3 on 2024-11-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Audio_Processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiodata",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
