# Generated by Django 5.1.2 on 2024-10-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Audio_Processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audio_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Audio_Processing.audiodata",
                    ),
                ),
            ],
        ),
    ]
