# Generated by Django 5.1.2 on 2024-10-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Drone_Management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealTimeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_type", models.CharField(max_length=50)),
                ("data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "drone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Drone_Management.drone",
                    ),
                ),
            ],
        ),
    ]
